# Copyright (c) 0235 Inc.
# This file is licensed under the karakuri_agent Personal Use & No Warranty License.
# Please see the LICENSE file in the project root.

services:
  karakuri-agent-server-dev:
    container_name: "karakuri-agent-server-dev"
    volumes:
      - ./:/home/karakuri/workspace/server
      - pip-cache:/home/karakuri/.cache/pip
      - pip-local:/home/karakuri/.local
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "8081:8080"
    tty: true
    environment:
      - PATH=/home/karakuri/.local/bin:${PATH}
    command: >
      bash -c "pip install --user --upgrade pip &&
             pip install --user --no-cache-dir --upgrade -r requirements.txt &&
             sleep infinity"
    depends_on:
      - valkey
    networks:
      - karakuri-agent-dev-network

  valkey:
    container_name: "karakuri-valkey-dev"
    image: valkey/valkey:8.0.2
    ports:
      - "6378:6379"
    command: valkey-server --requirepass ${VALKEY_PASSWORD}
    environment:
      - VALKEY_PASSWORD=${VALKEY_PASSWORD}
    networks:
      - karakuri-agent-dev-network
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - valkey_data:/data

volumes:
  valkey_data:
  pip-cache:
  pip-local:

networks:
  karakuri-agent-dev-network:
    driver: bridge
