# Copyright (c) 0235 Inc.
# This file is licensed under the karakuri_agent Personal Use & No Warranty License.
# Please see the LICENSE file in the project root.

services:
  karakuri-agent-server-dev:
    container_name: "karakuri-agent-server-dev"
    volumes:
      - ./:/home/karakuri/workspace/server
      - pip-cache:/home/karakuri/.cache/pip
      - pip-local:/home/karakuri/.local
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "8081:8080"
    tty: true
    environment:
      - PATH=/home/karakuri/.local/bin:${PATH}
    command: >
      bash -c "pip install --user --upgrade pip &&
             pip install --user --no-cache-dir --upgrade -r requirements.txt &&
             sleep infinity"
    depends_on:
      - redis
    networks:
      - karakuri-agent-dev-network

  redis:
    container_name: "karakuri-redis-dev"
    image: redis:7.2
    ports:
      - "6378:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - redis_data:/data
    networks:
      - karakuri-agent-dev-network

volumes:
  redis_data:
  pip-cache:
  pip-local:

networks:
  karakuri-agent-dev-network:
    driver: bridge
