# Copyright (c) 0235 Inc.
# This file is licensed under the karakuri_agent Personal Use & No Warranty License.
# Please see the LICENSE file in the project root.

FROM python:3.10-slim

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential libsndfile1 ffmpeg && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd -g 1000 karakuri && useradd -u 1000 -g karakuri karakuri

RUN mkdir -p /home/karakuri/.cache/pip && \
    mkdir -p /home/karakuri/.local && \
    chown -R karakuri:karakuri /home/karakuri

WORKDIR /home/karakuri/workspace/server
RUN chown karakuri:karakuri /home/karakuri/workspace/server

USER karakuri
