version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  access:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    filename: /app/logs/application.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  access_file:
    class: logging.handlers.RotatingFileHandler
    formatter: access
    filename: /app/logs/access.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  uvicorn:
    handlers: [console, file]
    level: INFO
  uvicorn.access:
    handlers: [access_file]
    level: INFO
    propagate: false
  watchfiles.main: 
    level: WARNING 
    handlers: [console, file]

root:
  level: INFO
  handlers: [console, file]
  propagate: no
