import 'package:karakuri_agent/models/key_value_pair.dart';
import 'package:karakuri_agent/services/default_param/default_param_service.dart';

class VoicevoxDefaultParamService extends DefaultParamService {
  @override
  List<KeyValuePair> get textmodels => [];

  @override
  List<KeyValuePair> get speechToTextModels => [];

  @override
  List<KeyValuePair> get textToSpeechModels => [
        KeyValuePair(key: 'default', value: 'default'),
      ];

  @override
  List<KeyValuePair> get textToSpeechVoices => [
        KeyValuePair(key: '2', value: '四国めたん:ノーマル'),
        KeyValuePair(key: '0', value: '四国めたん:あまあま'),
        KeyValuePair(key: '6', value: '四国めたん:ツンツン'),
        KeyValuePair(key: '4', value: '四国めたん:セクシー'),
        KeyValuePair(key: '36', value: '四国めたん:ささやき'),
        KeyValuePair(key: '37', value: '四国めたん:ヒソヒソ'),
        KeyValuePair(key: '3', value: 'ずんだもん:ノーマル'),
        KeyValuePair(key: '1', value: 'ずんだもん:あまあま'),
        KeyValuePair(key: '7', value: 'ずんだもん:ツンツン'),
        KeyValuePair(key: '5', value: 'ずんだもん:セクシー'),
        KeyValuePair(key: '22', value: 'ずんだもん:ささやき'),
        KeyValuePair(key: '38', value: 'ずんだもん:ヒソヒソ'),
        KeyValuePair(key: '75', value: 'ずんだもん:ヘロヘロ'),
        KeyValuePair(key: '76', value: 'ずんだもん:なみだめ'),
        KeyValuePair(key: '8', value: '春日部つむぎ:ノーマル'),
        KeyValuePair(key: '10', value: '雨晴はう:ノーマル'),
        KeyValuePair(key: '9', value: '波音リツ:ノーマル'),
        KeyValuePair(key: '65', value: '波音リツ:クイーン'),
        KeyValuePair(key: '11', value: '玄野武宏:ノーマル'),
        KeyValuePair(key: '39', value: '玄野武宏:喜び'),
        KeyValuePair(key: '40', value: '玄野武宏:ツンギレ'),
        KeyValuePair(key: '41', value: '玄野武宏:悲しみ'),
        KeyValuePair(key: '12', value: '白上虎太郎:ふつう'),
        KeyValuePair(key: '32', value: '白上虎太郎:わーい'),
        KeyValuePair(key: '33', value: '白上虎太郎:びくびく'),
        KeyValuePair(key: '34', value: '白上虎太郎:おこ'),
        KeyValuePair(key: '35', value: '白上虎太郎:びえーん'),
        KeyValuePair(key: '13', value: '青山龍星:ノーマル'),
        KeyValuePair(key: '81', value: '青山龍星:熱血'),
        KeyValuePair(key: '82', value: '青山龍星:不機嫌'),
        KeyValuePair(key: '83', value: '青山龍星:喜び'),
        KeyValuePair(key: '84', value: '青山龍星:しっとり'),
        KeyValuePair(key: '85', value: '青山龍星:かなしみ'),
        KeyValuePair(key: '86', value: '青山龍星:囁き'),
        KeyValuePair(key: '14', value: '冥鳴ひまり:ノーマル'),
        KeyValuePair(key: '16', value: '九州そら:ノーマル'),
        KeyValuePair(key: '15', value: '九州そら:あまあま'),
        KeyValuePair(key: '18', value: '九州そら:ツンツン'),
        KeyValuePair(key: '17', value: '九州そら:セクシー'),
        KeyValuePair(key: '19', value: '九州そら:ささやき'),
        KeyValuePair(key: '20', value: 'もち子さん:ノーマル'),
        KeyValuePair(key: '66', value: 'もち子さん:セクシー／あん子'),
        KeyValuePair(key: '77', value: 'もち子さん:泣き'),
        KeyValuePair(key: '78', value: 'もち子さん:怒り'),
        KeyValuePair(key: '79', value: 'もち子さん:喜び'),
        KeyValuePair(key: '80', value: 'もち子さん:のんびり'),
        KeyValuePair(key: '21', value: '剣崎雌雄:ノーマル'),
        KeyValuePair(key: '23', value: 'WhiteCUL:ノーマル'),
        KeyValuePair(key: '24', value: 'WhiteCUL:たのしい'),
        KeyValuePair(key: '25', value: 'WhiteCUL:かなしい'),
        KeyValuePair(key: '26', value: 'WhiteCUL:びえーん'),
        KeyValuePair(key: '27', value: '後鬼:人間ver.'),
        KeyValuePair(key: '28', value: '後鬼:ぬいぐるみver.'),
        KeyValuePair(key: '87', value: '後鬼:人間（怒り）ver.'),
        KeyValuePair(key: '88', value: '後鬼:鬼ver.'),
        KeyValuePair(key: '29', value: 'No.7:ノーマル'),
        KeyValuePair(key: '30', value: 'No.7:アナウンス'),
        KeyValuePair(key: '31', value: 'No.7:読み聞かせ'),
        KeyValuePair(key: '42', value: 'ちび式じい:ノーマル'),
        KeyValuePair(key: '43', value: '櫻歌ミコ:ノーマル'),
        KeyValuePair(key: '44', value: '櫻歌ミコ:第二形態'),
        KeyValuePair(key: '45', value: '櫻歌ミコ:ロリ'),
        KeyValuePair(key: '46', value: '小夜/SAYO:ノーマル'),
        KeyValuePair(key: '47', value: 'ナースロボ＿タイプＴ:ノーマル'),
        KeyValuePair(key: '48', value: 'ナースロボ＿タイプＴ:楽々'),
        KeyValuePair(key: '49', value: 'ナースロボ＿タイプＴ:恐怖'),
        KeyValuePair(key: '50', value: 'ナースロボ＿タイプＴ:内緒話'),
        KeyValuePair(key: '51', value: '†聖騎士 紅桜†:ノーマル'),
        KeyValuePair(key: '52', value: '雀松朱司:ノーマル'),
        KeyValuePair(key: '53', value: '麒ヶ島宗麟:ノーマル'),
        KeyValuePair(key: '54', value: '春歌ナナ:ノーマル'),
        KeyValuePair(key: '55', value: '猫使アル:ノーマル'),
        KeyValuePair(key: '56', value: '猫使アル:おちつき'),
        KeyValuePair(key: '57', value: '猫使アル:うきうき'),
        KeyValuePair(key: '58', value: '猫使ビィ:ノーマル'),
        KeyValuePair(key: '59', value: '猫使ビィ:おちつき'),
        KeyValuePair(key: '60', value: '猫使ビィ:人見知り'),
        KeyValuePair(key: '61', value: '中国うさぎ:ノーマル'),
        KeyValuePair(key: '62', value: '中国うさぎ:おどろき'),
        KeyValuePair(key: '63', value: '中国うさぎ:こわがり'),
        KeyValuePair(key: '64', value: '中国うさぎ:へろへろ'),
        KeyValuePair(key: '67', value: '栗田まろん:ノーマル'),
        KeyValuePair(key: '68', value: 'あいえるたん:ノーマル'),
        KeyValuePair(key: '69', value: '満別花丸:ノーマル'),
        KeyValuePair(key: '70', value: '満別花丸:元気'),
        KeyValuePair(key: '71', value: '満別花丸:ささやき'),
        KeyValuePair(key: '72', value: '満別花丸:ぶりっ子'),
        KeyValuePair(key: '73', value: '満別花丸:ボーイ'),
        KeyValuePair(key: '74', value: '琴詠ニア:ノーマル'),
        KeyValuePair(key: '89', value: 'Voidoll:ノーマル'),
      ];
}
